name: Mick Traen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16109
title: Mick Traen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1819'
    - '#a21c28'
    - '#c8858b'
    - '#a1597c'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
