name: Mick Traen
favicon: null
layout_spectrum: 0.11073275050148368
typography_spectrum: 0.32456780108623207
title: Mr.Traen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6142220983747393
  lightness: 0.5870254123583436
  saturation: 0.8036934135016054
  rhythmicContrast: 0.8159792744554579
purpose: []
